export interface LeaderboardEntry {
  rank: number;
  domain: string;
  category: string;
  geoScore: number;
  citationWinRate: number;
  zeroClickResilience: number;
  trend: 'up' | 'down' | 'flat';
  trendDelta: number;
  scanCount: number;
  /** True when the score came from a live crawl; false = deterministic fallback estimate */
  isLiveScanned?: boolean;
  lastScanned?: string;
}

const RAW_ENTRIES: LeaderboardEntry[] = [
  // Top Tier (95 - 98)
  { rank: 1, domain: 'openai.com', category: 'AI/Tech', geoScore: 98, citationWinRate: 97, zeroClickResilience: 95, trend: 'up', trendDelta: 3, scanCount: 28 },
  { rank: 2, domain: 'perplexity.ai', category: 'AI/Tech', geoScore: 97, citationWinRate: 96, zeroClickResilience: 94, trend: 'up', trendDelta: 4, scanCount: 22 },
  { rank: 3, domain: 'github.com', category: 'Developer', geoScore: 96, citationWinRate: 95, zeroClickResilience: 93, trend: 'flat', trendDelta: 0, scanCount: 31 },
  { rank: 4, domain: 'vercel.com', category: 'Developer', geoScore: 96, citationWinRate: 94, zeroClickResilience: 92, trend: 'up', trendDelta: 5, scanCount: 25 },
  { rank: 5, domain: 'stripe.com', category: 'Fintech', geoScore: 95, citationWinRate: 93, zeroClickResilience: 91, trend: 'up', trendDelta: 2, scanCount: 29 },
  { rank: 6, domain: 'cloudflare.com', category: 'Developer', geoScore: 95, citationWinRate: 93, zeroClickResilience: 90, trend: 'up', trendDelta: 2, scanCount: 24 },
  { rank: 7, domain: 'anthropic.com', category: 'AI/Tech', geoScore: 95, citationWinRate: 93, zeroClickResilience: 91, trend: 'up', trendDelta: 3, scanCount: 19 },
  { rank: 8, domain: 'amazon.com', category: 'E-Commerce', geoScore: 94, citationWinRate: 92, zeroClickResilience: 90, trend: 'flat', trendDelta: 0, scanCount: 34 },
  { rank: 9, domain: 'shopify.com', category: 'E-Commerce', geoScore: 94, citationWinRate: 91, zeroClickResilience: 89, trend: 'down', trendDelta: -1, scanCount: 26 },
  { rank: 10, domain: 'slack.com', category: 'SaaS/Tools', geoScore: 93, citationWinRate: 91, zeroClickResilience: 89, trend: 'flat', trendDelta: 0, scanCount: 22 },
  { rank: 11, domain: 'figma.com', category: 'SaaS/Design', geoScore: 93, citationWinRate: 90, zeroClickResilience: 88, trend: 'up', trendDelta: 2, scanCount: 20 },
  { rank: 12, domain: 'linear.app', category: 'SaaS/Tools', geoScore: 93, citationWinRate: 91, zeroClickResilience: 88, trend: 'up', trendDelta: 4, scanCount: 18 },
  { rank: 13, domain: 'cursor.com', category: 'AI/Tech', geoScore: 93, citationWinRate: 90, zeroClickResilience: 89, trend: 'up', trendDelta: 6, scanCount: 16 },
  { rank: 14, domain: 'hubspot.com', category: 'SaaS/Tools', geoScore: 92, citationWinRate: 89, zeroClickResilience: 87, trend: 'up', trendDelta: 1, scanCount: 21 },
  { rank: 15, domain: 'huggingface.co', category: 'AI/Tech', geoScore: 92, citationWinRate: 90, zeroClickResilience: 88, trend: 'flat', trendDelta: 0, scanCount: 17 },
  { rank: 16, domain: 'docker.com', category: 'Developer', geoScore: 92, citationWinRate: 89, zeroClickResilience: 86, trend: 'down', trendDelta: -1, scanCount: 15 },
  { rank: 17, domain: 'supabase.com', category: 'Developer', geoScore: 92, citationWinRate: 90, zeroClickResilience: 88, trend: 'up', trendDelta: 4, scanCount: 23 },
  { rank: 18, domain: 'canva.com', category: 'SaaS/Design', geoScore: 92, citationWinRate: 89, zeroClickResilience: 87, trend: 'up', trendDelta: 2, scanCount: 21 },
  { rank: 19, domain: 'midjourney.com', category: 'AI/Tech', geoScore: 91, citationWinRate: 89, zeroClickResilience: 87, trend: 'up', trendDelta: 3, scanCount: 14 },
  { rank: 20, domain: 'notion.so', category: 'SaaS/Tools', geoScore: 91, citationWinRate: 88, zeroClickResilience: 86, trend: 'down', trendDelta: -1, scanCount: 27 },
  { rank: 21, domain: 'plaid.com', category: 'Fintech', geoScore: 91, citationWinRate: 89, zeroClickResilience: 87, trend: 'flat', trendDelta: 0, scanCount: 16 },
  { rank: 22, domain: 'datadoghq.com', category: 'Developer', geoScore: 91, citationWinRate: 88, zeroClickResilience: 86, trend: 'up', trendDelta: 1, scanCount: 18 },
  { rank: 23, domain: 'posthog.com', category: 'Developer', geoScore: 90, citationWinRate: 88, zeroClickResilience: 86, trend: 'up', trendDelta: 4, scanCount: 19 },
  { rank: 24, domain: 'postman.com', category: 'Developer', geoScore: 90, citationWinRate: 87, zeroClickResilience: 85, trend: 'flat', trendDelta: 0, scanCount: 15 },
  { rank: 25, domain: 'mistral.ai', category: 'AI/Tech', geoScore: 90, citationWinRate: 88, zeroClickResilience: 87, trend: 'up', trendDelta: 3, scanCount: 13 },
  { rank: 26, domain: 'wise.com', category: 'Fintech', geoScore: 90, citationWinRate: 88, zeroClickResilience: 85, trend: 'up', trendDelta: 2, scanCount: 17 },
  { rank: 27, domain: 'ramp.com', category: 'Fintech', geoScore: 90, citationWinRate: 87, zeroClickResilience: 86, trend: 'up', trendDelta: 4, scanCount: 15 },
  { rank: 28, domain: 'webflow.com', category: 'SaaS/Design', geoScore: 90, citationWinRate: 87, zeroClickResilience: 85, trend: 'flat', trendDelta: 0, scanCount: 19 },
  { rank: 29, domain: 'neon.tech', category: 'Developer', geoScore: 89, citationWinRate: 86, zeroClickResilience: 85, trend: 'up', trendDelta: 3, scanCount: 14 },
  { rank: 30, domain: 'segment.com', category: 'Developer', geoScore: 89, citationWinRate: 86, zeroClickResilience: 84, trend: 'flat', trendDelta: 0, scanCount: 16 },
  { rank: 31, domain: 'turso.tech', category: 'Developer', geoScore: 89, citationWinRate: 87, zeroClickResilience: 85, trend: 'up', trendDelta: 4, scanCount: 14 },
  { rank: 32, domain: 'intercom.com', category: 'SaaS/Tools', geoScore: 89, citationWinRate: 86, zeroClickResilience: 84, trend: 'up', trendDelta: 2, scanCount: 18 },
  { rank: 33, domain: 'framer.com', category: 'SaaS/Design', geoScore: 89, citationWinRate: 86, zeroClickResilience: 84, trend: 'up', trendDelta: 3, scanCount: 17 },
  { rank: 34, domain: 'cohere.com', category: 'AI/Tech', geoScore: 89, citationWinRate: 86, zeroClickResilience: 84, trend: 'down', trendDelta: -1, scanCount: 11 },
  { rank: 35, domain: 'adobe.com', category: 'SaaS/Design', geoScore: 89, citationWinRate: 86, zeroClickResilience: 85, trend: 'flat', trendDelta: 0, scanCount: 22 },
  { rank: 36, domain: 'brex.com', category: 'Fintech', geoScore: 88, citationWinRate: 86, zeroClickResilience: 84, trend: 'up', trendDelta: 3, scanCount: 15 },
  { rank: 37, domain: 'paypal.com', category: 'Fintech', geoScore: 88, citationWinRate: 85, zeroClickResilience: 84, trend: 'flat', trendDelta: 0, scanCount: 26 },
  { rank: 38, domain: 'revolut.com', category: 'Fintech', geoScore: 88, citationWinRate: 86, zeroClickResilience: 84, trend: 'up', trendDelta: 3, scanCount: 18 },
  { rank: 39, domain: 'miro.com', category: 'SaaS/Tools', geoScore: 88, citationWinRate: 85, zeroClickResilience: 83, trend: 'up', trendDelta: 2, scanCount: 16 },
  { rank: 40, domain: 'klaviyo.com', category: 'E-Commerce', geoScore: 88, citationWinRate: 85, zeroClickResilience: 84, trend: 'flat', trendDelta: 0, scanCount: 15 },
  { rank: 41, domain: 'airtable.com', category: 'SaaS/Tools', geoScore: 88, citationWinRate: 85, zeroClickResilience: 83, trend: 'flat', trendDelta: 0, scanCount: 17 },
  { rank: 42, domain: 'scale.com', category: 'AI/Tech', geoScore: 88, citationWinRate: 85, zeroClickResilience: 83, trend: 'up', trendDelta: 2, scanCount: 12 },
  { rank: 43, domain: 'cal.com', category: 'Developer', geoScore: 88, citationWinRate: 85, zeroClickResilience: 83, trend: 'up', trendDelta: 3, scanCount: 14 },
  { rank: 44, domain: 'groq.com', category: 'AI/Tech', geoScore: 88, citationWinRate: 86, zeroClickResilience: 84, trend: 'up', trendDelta: 5, scanCount: 13 },
  { rank: 45, domain: 'elevenlabs.io', category: 'AI/Tech', geoScore: 87, citationWinRate: 85, zeroClickResilience: 84, trend: 'up', trendDelta: 4, scanCount: 15 },
  { rank: 46, domain: 'gitlab.com', category: 'Developer', geoScore: 87, citationWinRate: 85, zeroClickResilience: 83, trend: 'flat', trendDelta: 0, scanCount: 18 },
  { rank: 47, domain: 'dub.co', category: 'Developer', geoScore: 87, citationWinRate: 84, zeroClickResilience: 82, trend: 'up', trendDelta: 5, scanCount: 16 },
  { rank: 48, domain: 'railway.app', category: 'Developer', geoScore: 87, citationWinRate: 84, zeroClickResilience: 82, trend: 'up', trendDelta: 2, scanCount: 13 },
  { rank: 49, domain: 'adyen.com', category: 'Fintech', geoScore: 87, citationWinRate: 84, zeroClickResilience: 82, trend: 'flat', trendDelta: 0, scanCount: 14 },
  { rank: 50, domain: 'asana.com', category: 'SaaS/Tools', geoScore: 87, citationWinRate: 84, zeroClickResilience: 82, trend: 'down', trendDelta: -1, scanCount: 16 },
  { rank: 51, domain: 'bigcommerce.com', category: 'E-Commerce', geoScore: 86, citationWinRate: 83, zeroClickResilience: 81, trend: 'down', trendDelta: -2, scanCount: 13 },
  { rank: 52, domain: 'clickup.com', category: 'SaaS/Tools', geoScore: 86, citationWinRate: 83, zeroClickResilience: 81, trend: 'up', trendDelta: 2, scanCount: 16 },
  { rank: 53, domain: 'mercury.com', category: 'Fintech', geoScore: 86, citationWinRate: 83, zeroClickResilience: 81, trend: 'up', trendDelta: 1, scanCount: 14 },
  { rank: 54, domain: 'coinbase.com', category: 'Fintech', geoScore: 86, citationWinRate: 83, zeroClickResilience: 82, trend: 'flat', trendDelta: 0, scanCount: 20 },
  { rank: 55, domain: 'runwayml.com', category: 'AI/Tech', geoScore: 86, citationWinRate: 84, zeroClickResilience: 82, trend: 'up', trendDelta: 4, scanCount: 12 },
  { rank: 56, domain: 'resend.com', category: 'Developer', geoScore: 86, citationWinRate: 84, zeroClickResilience: 82, trend: 'up', trendDelta: 5, scanCount: 15 },
  { rank: 57, domain: 'sentry.io', category: 'Developer', geoScore: 86, citationWinRate: 83, zeroClickResilience: 81, trend: 'up', trendDelta: 1, scanCount: 17 },
  { rank: 58, domain: 'netlify.com', category: 'Developer', geoScore: 86, citationWinRate: 83, zeroClickResilience: 81, trend: 'down', trendDelta: -1, scanCount: 16 },
  { rank: 59, domain: 'atlassian.com', category: 'SaaS/Tools', geoScore: 85, citationWinRate: 82, zeroClickResilience: 80, trend: 'flat', trendDelta: 0, scanCount: 22 },
  { rank: 60, domain: 'etsy.com', category: 'E-Commerce', geoScore: 85, citationWinRate: 82, zeroClickResilience: 81, trend: 'up', trendDelta: 1, scanCount: 18 },
  { rank: 61, domain: 'zoom.us', category: 'SaaS/Tools', geoScore: 85, citationWinRate: 82, zeroClickResilience: 80, trend: 'down', trendDelta: -1, scanCount: 24 },
  { rank: 62, domain: 'monday.com', category: 'SaaS/Tools', geoScore: 85, citationWinRate: 82, zeroClickResilience: 80, trend: 'up', trendDelta: 2, scanCount: 17 },
  { rank: 63, domain: 'zapier.com', category: 'SaaS/Tools', geoScore: 85, citationWinRate: 83, zeroClickResilience: 81, trend: 'up', trendDelta: 2, scanCount: 19 },
  { rank: 64, domain: 'loom.com', category: 'SaaS/Tools', geoScore: 85, citationWinRate: 82, zeroClickResilience: 80, trend: 'flat', trendDelta: 0, scanCount: 14 },
  { rank: 65, domain: 'robinhood.com', category: 'Fintech', geoScore: 85, citationWinRate: 82, zeroClickResilience: 80, trend: 'up', trendDelta: 2, scanCount: 15 },
  { rank: 66, domain: 'squareup.com', category: 'Fintech', geoScore: 85, citationWinRate: 82, zeroClickResilience: 81, trend: 'flat', trendDelta: 0, scanCount: 19 },
  { rank: 67, domain: 'stability.ai', category: 'AI/Tech', geoScore: 85, citationWinRate: 82, zeroClickResilience: 81, trend: 'down', trendDelta: -2, scanCount: 13 },
  { rank: 68, domain: 'replicate.com', category: 'AI/Tech', geoScore: 85, citationWinRate: 83, zeroClickResilience: 81, trend: 'up', trendDelta: 4, scanCount: 12 },
  { rank: 69, domain: 'deepseek.com', category: 'AI/Tech', geoScore: 85, citationWinRate: 83, zeroClickResilience: 82, trend: 'up', trendDelta: 6, scanCount: 11 },
  { rank: 70, domain: 'prisma.io', category: 'Developer', geoScore: 85, citationWinRate: 83, zeroClickResilience: 81, trend: 'up', trendDelta: 2, scanCount: 16 },
  { rank: 71, domain: 'clerk.com', category: 'Developer', geoScore: 85, citationWinRate: 83, zeroClickResilience: 82, trend: 'up', trendDelta: 4, scanCount: 15 },
  { rank: 72, domain: 'auth0.com', category: 'Developer', geoScore: 85, citationWinRate: 82, zeroClickResilience: 80, trend: 'flat', trendDelta: 0, scanCount: 18 },
  { rank: 73, domain: 'bun.sh', category: 'Developer', geoScore: 84, citationWinRate: 82, zeroClickResilience: 80, trend: 'up', trendDelta: 3, scanCount: 14 },
  { rank: 74, domain: 'deno.com', category: 'Developer', geoScore: 84, citationWinRate: 81, zeroClickResilience: 79, trend: 'up', trendDelta: 1, scanCount: 13 },
  { rank: 75, domain: 'render.com', category: 'Developer', geoScore: 84, citationWinRate: 81, zeroClickResilience: 80, trend: 'up', trendDelta: 2, scanCount: 12 },
  { rank: 76, domain: 'fly.io', category: 'Developer', geoScore: 84, citationWinRate: 81, zeroClickResilience: 79, trend: 'up', trendDelta: 2, scanCount: 14 },
  { rank: 77, domain: 'upstash.com', category: 'Developer', geoScore: 84, citationWinRate: 82, zeroClickResilience: 80, trend: 'up', trendDelta: 3, scanCount: 11 },
  { rank: 78, domain: 'pinecone.io', category: 'AI/Tech', geoScore: 84, citationWinRate: 81, zeroClickResilience: 80, trend: 'up', trendDelta: 3, scanCount: 12 },
  { rank: 79, domain: 'qdrant.tech', category: 'AI/Tech', geoScore: 84, citationWinRate: 81, zeroClickResilience: 79, trend: 'up', trendDelta: 4, scanCount: 10 },
  { rank: 80, domain: 'weaviate.io', category: 'AI/Tech', geoScore: 84, citationWinRate: 81, zeroClickResilience: 79, trend: 'up', trendDelta: 2, scanCount: 11 },
  { rank: 81, domain: 'spline.design', category: 'SaaS/Design', geoScore: 84, citationWinRate: 81, zeroClickResilience: 79, trend: 'up', trendDelta: 4, scanCount: 12 },
  { rank: 82, domain: 'sketch.com', category: 'SaaS/Design', geoScore: 84, citationWinRate: 80, zeroClickResilience: 78, trend: 'down', trendDelta: -1, scanCount: 14 },
  { rank: 83, domain: 'dribbble.com', category: 'SaaS/Design', geoScore: 84, citationWinRate: 81, zeroClickResilience: 79, trend: 'flat', trendDelta: 0, scanCount: 17 },
  { rank: 84, domain: 'behance.net', category: 'SaaS/Design', geoScore: 84, citationWinRate: 81, zeroClickResilience: 80, trend: 'flat', trendDelta: 0, scanCount: 18 },
  { rank: 85, domain: 'ebay.com', category: 'E-Commerce', geoScore: 84, citationWinRate: 80, zeroClickResilience: 78, trend: 'down', trendDelta: -1, scanCount: 22 },
  { rank: 86, domain: 'target.com', category: 'E-Commerce', geoScore: 84, citationWinRate: 81, zeroClickResilience: 79, trend: 'flat', trendDelta: 0, scanCount: 20 },
  { rank: 87, domain: 'walmart.com', category: 'E-Commerce', geoScore: 84, citationWinRate: 81, zeroClickResilience: 79, trend: 'up', trendDelta: 1, scanCount: 23 },
  { rank: 88, domain: 'bill.com', category: 'Fintech', geoScore: 84, citationWinRate: 81, zeroClickResilience: 79, trend: 'flat', trendDelta: 0, scanCount: 14 },
  { rank: 89, domain: 'klarna.com', category: 'Fintech', geoScore: 84, citationWinRate: 81, zeroClickResilience: 79, trend: 'up', trendDelta: 2, scanCount: 16 },
  { rank: 90, domain: 'grammarly.com', category: 'SaaS/Tools', geoScore: 83, citationWinRate: 80, zeroClickResilience: 78, trend: 'flat', trendDelta: 0, scanCount: 19 },
  { rank: 91, domain: 'calendly.com', category: 'SaaS/Tools', geoScore: 83, citationWinRate: 80, zeroClickResilience: 78, trend: 'up', trendDelta: 1, scanCount: 18 },
  { rank: 92, domain: 'basecamp.com', category: 'SaaS/Tools', geoScore: 83, citationWinRate: 80, zeroClickResilience: 77, trend: 'flat', trendDelta: 0, scanCount: 13 },
  { rank: 93, domain: 'coda.io', category: 'SaaS/Tools', geoScore: 83, citationWinRate: 80, zeroClickResilience: 78, trend: 'up', trendDelta: 2, scanCount: 14 },
  { rank: 94, domain: 'front.com', category: 'SaaS/Tools', geoScore: 83, citationWinRate: 79, zeroClickResilience: 77, trend: 'up', trendDelta: 1, scanCount: 12 },
  { rank: 95, domain: 'together.ai', category: 'AI/Tech', geoScore: 83, citationWinRate: 80, zeroClickResilience: 79, trend: 'up', trendDelta: 3, scanCount: 10 },
  { rank: 96, domain: 'langchain.com', category: 'AI/Tech', geoScore: 83, citationWinRate: 81, zeroClickResilience: 79, trend: 'up', trendDelta: 4, scanCount: 13 },
  { rank: 97, domain: 'llamaindex.ai', category: 'AI/Tech', geoScore: 83, citationWinRate: 80, zeroClickResilience: 78, trend: 'up', trendDelta: 3, scanCount: 11 },
  { rank: 98, domain: 'planetscale.com', category: 'Developer', geoScore: 83, citationWinRate: 80, zeroClickResilience: 78, trend: 'down', trendDelta: -1, scanCount: 14 },
  { rank: 99, domain: 'convex.dev', category: 'Developer', geoScore: 83, citationWinRate: 80, zeroClickResilience: 78, trend: 'up', trendDelta: 4, scanCount: 11 },
  { rank: 100, domain: 'mintlify.com', category: 'Developer', geoScore: 83, citationWinRate: 81, zeroClickResilience: 79, trend: 'up', trendDelta: 5, scanCount: 12 },
  { rank: 101, domain: 'lottiefiles.com', category: 'SaaS/Design', geoScore: 83, citationWinRate: 79, zeroClickResilience: 77, trend: 'up', trendDelta: 2, scanCount: 13 },
  { rank: 102, domain: 'penpot.app', category: 'SaaS/Design', geoScore: 83, citationWinRate: 80, zeroClickResilience: 78, trend: 'up', trendDelta: 3, scanCount: 11 },
  { rank: 103, domain: 'nike.com', category: 'E-Commerce', geoScore: 83, citationWinRate: 80, zeroClickResilience: 78, trend: 'flat', trendDelta: 0, scanCount: 24 },
  { rank: 104, domain: 'chime.com', category: 'Fintech', geoScore: 83, citationWinRate: 79, zeroClickResilience: 77, trend: 'up', trendDelta: 1, scanCount: 14 },
  { rank: 105, domain: 'affirm.com', category: 'Fintech', geoScore: 83, citationWinRate: 80, zeroClickResilience: 78, trend: 'up', trendDelta: 2, scanCount: 15 },
  { rank: 106, domain: 'checkout.com', category: 'Fintech', geoScore: 83, citationWinRate: 80, zeroClickResilience: 77, trend: 'flat', trendDelta: 0, scanCount: 13 },
  { rank: 107, domain: 'docusign.com', category: 'SaaS/Tools', geoScore: 82, citationWinRate: 79, zeroClickResilience: 77, trend: 'flat', trendDelta: 0, scanCount: 18 },
  { rank: 108, domain: 'box.com', category: 'SaaS/Tools', geoScore: 82, citationWinRate: 78, zeroClickResilience: 76, trend: 'down', trendDelta: -1, scanCount: 16 },
  { rank: 109, domain: 'dropbox.com', category: 'SaaS/Tools', geoScore: 82, citationWinRate: 79, zeroClickResilience: 77, trend: 'flat', trendDelta: 0, scanCount: 21 },
  { rank: 110, domain: 'salesforce.com', category: 'SaaS/Tools', geoScore: 82, citationWinRate: 79, zeroClickResilience: 77, trend: 'flat', trendDelta: 0, scanCount: 26 },
  { rank: 111, domain: 'zendesk.com', category: 'SaaS/Tools', geoScore: 82, citationWinRate: 79, zeroClickResilience: 76, trend: 'down', trendDelta: -1, scanCount: 17 },
  { rank: 112, domain: 'character.ai', category: 'AI/Tech', geoScore: 82, citationWinRate: 79, zeroClickResilience: 77, trend: 'down', trendDelta: -2, scanCount: 15 },
  { rank: 113, domain: 'jasper.ai', category: 'AI/Tech', geoScore: 82, citationWinRate: 78, zeroClickResilience: 76, trend: 'down', trendDelta: -1, scanCount: 14 },
  { rank: 114, domain: 'deepgram.com', category: 'AI/Tech', geoScore: 82, citationWinRate: 79, zeroClickResilience: 78, trend: 'up', trendDelta: 3, scanCount: 10 },
  { rank: 115, domain: 'poe.com', category: 'AI/Tech', geoScore: 82, citationWinRate: 79, zeroClickResilience: 77, trend: 'up', trendDelta: 2, scanCount: 12 },
  { rank: 116, domain: 'phind.com', category: 'AI/Tech', geoScore: 82, citationWinRate: 80, zeroClickResilience: 78, trend: 'up', trendDelta: 4, scanCount: 11 },
  { rank: 117, domain: 'trigger.dev', category: 'Developer', geoScore: 82, citationWinRate: 79, zeroClickResilience: 77, trend: 'up', trendDelta: 3, scanCount: 9 },
  { rank: 118, domain: 'inngest.com', category: 'Developer', geoScore: 82, citationWinRate: 79, zeroClickResilience: 77, trend: 'up', trendDelta: 2, scanCount: 10 },
  { rank: 119, domain: 'liveblocks.io', category: 'Developer', geoScore: 82, citationWinRate: 79, zeroClickResilience: 77, trend: 'up', trendDelta: 3, scanCount: 8 },
  { rank: 120, domain: 'rive.app', category: 'SaaS/Design', geoScore: 82, citationWinRate: 79, zeroClickResilience: 77, trend: 'up', trendDelta: 4, scanCount: 10 },
  { rank: 121, domain: 'blender.org', category: 'SaaS/Design', geoScore: 82, citationWinRate: 79, zeroClickResilience: 78, trend: 'flat', trendDelta: 0, scanCount: 16 },
  { rank: 122, domain: 'unsplash.com', category: 'SaaS/Design', geoScore: 82, citationWinRate: 79, zeroClickResilience: 77, trend: 'flat', trendDelta: 0, scanCount: 18 },
  { rank: 123, domain: 'asos.com', category: 'E-Commerce', geoScore: 82, citationWinRate: 78, zeroClickResilience: 76, trend: 'down', trendDelta: -1, scanCount: 16 },
  { rank: 124, domain: 'bestbuy.com', category: 'E-Commerce', geoScore: 82, citationWinRate: 78, zeroClickResilience: 76, trend: 'flat', trendDelta: 0, scanCount: 17 },
  { rank: 125, domain: 'wayfair.com', category: 'E-Commerce', geoScore: 82, citationWinRate: 78, zeroClickResilience: 76, trend: 'down', trendDelta: -1, scanCount: 15 },
  { rank: 126, domain: 'toasttab.com', category: 'Fintech', geoScore: 82, citationWinRate: 79, zeroClickResilience: 77, trend: 'up', trendDelta: 2, scanCount: 14 },
  { rank: 127, domain: 'carta.com', category: 'Fintech', geoScore: 82, citationWinRate: 78, zeroClickResilience: 76, trend: 'flat', trendDelta: 0, scanCount: 15 },
  { rank: 128, domain: 'gusto.com', category: 'Fintech', geoScore: 82, citationWinRate: 79, zeroClickResilience: 77, trend: 'up', trendDelta: 1, scanCount: 16 },
  { rank: 129, domain: 'deel.com', category: 'Fintech', geoScore: 82, citationWinRate: 79, zeroClickResilience: 77, trend: 'up', trendDelta: 3, scanCount: 15 },
  { rank: 130, domain: 'retool.com', category: 'SaaS/Tools', geoScore: 81, citationWinRate: 78, zeroClickResilience: 76, trend: 'up', trendDelta: 2, scanCount: 14 },
  { rank: 131, domain: 'make.com', category: 'SaaS/Tools', geoScore: 81, citationWinRate: 78, zeroClickResilience: 75, trend: 'up', trendDelta: 2, scanCount: 13 },
  { rank: 132, domain: 'raycast.com', category: 'SaaS/Tools', geoScore: 81, citationWinRate: 79, zeroClickResilience: 77, trend: 'up', trendDelta: 5, scanCount: 14 },
  { rank: 133, domain: 'superhuman.com', category: 'SaaS/Tools', geoScore: 81, citationWinRate: 78, zeroClickResilience: 76, trend: 'flat', trendDelta: 0, scanCount: 12 },
  { rank: 134, domain: 'pitch.com', category: 'SaaS/Tools', geoScore: 81, citationWinRate: 77, zeroClickResilience: 75, trend: 'flat', trendDelta: 0, scanCount: 11 },
  { rank: 135, domain: 'harvey.ai', category: 'AI/Tech', geoScore: 81, citationWinRate: 78, zeroClickResilience: 76, trend: 'up', trendDelta: 4, scanCount: 8 },
  { rank: 136, domain: 'writer.com', category: 'AI/Tech', geoScore: 81, citationWinRate: 77, zeroClickResilience: 75, trend: 'up', trendDelta: 1, scanCount: 9 },
  { rank: 137, domain: 'inkeep.com', category: 'Developer', geoScore: 81, citationWinRate: 78, zeroClickResilience: 76, trend: 'up', trendDelta: 3, scanCount: 8 },
  { rank: 138, domain: 'hashicorp.com', category: 'Developer', geoScore: 81, citationWinRate: 78, zeroClickResilience: 76, trend: 'flat', trendDelta: 0, scanCount: 14 },
  { rank: 139, domain: 'freepik.com', category: 'SaaS/Design', geoScore: 81, citationWinRate: 77, zeroClickResilience: 75, trend: 'flat', trendDelta: 0, scanCount: 15 },
  { rank: 140, domain: 'icons8.com', category: 'SaaS/Design', geoScore: 81, citationWinRate: 77, zeroClickResilience: 75, trend: 'flat', trendDelta: 0, scanCount: 13 },
  { rank: 141, domain: 'mobbin.com', category: 'SaaS/Design', geoScore: 81, citationWinRate: 78, zeroClickResilience: 76, trend: 'up', trendDelta: 3, scanCount: 11 },
  { rank: 142, domain: 'relume.io', category: 'SaaS/Design', geoScore: 81, citationWinRate: 78, zeroClickResilience: 76, trend: 'up', trendDelta: 4, scanCount: 10 },
  { rank: 143, domain: 'zalando.com', category: 'E-Commerce', geoScore: 81, citationWinRate: 77, zeroClickResilience: 75, trend: 'down', trendDelta: -1, scanCount: 14 },
  { rank: 144, domain: 'alibaba.com', category: 'E-Commerce', geoScore: 81, citationWinRate: 77, zeroClickResilience: 76, trend: 'flat', trendDelta: 0, scanCount: 19 },
  { rank: 145, domain: 'shopee.com', category: 'E-Commerce', geoScore: 81, citationWinRate: 77, zeroClickResilience: 75, trend: 'up', trendDelta: 1, scanCount: 16 },
  { rank: 146, domain: 'remote.com', category: 'Fintech', geoScore: 81, citationWinRate: 77, zeroClickResilience: 75, trend: 'up', trendDelta: 2, scanCount: 12 },
  { rank: 147, domain: 'melio.com', category: 'Fintech', geoScore: 81, citationWinRate: 77, zeroClickResilience: 75, trend: 'flat', trendDelta: 0, scanCount: 10 },
  { rank: 148, domain: 'moderntreasury.com', category: 'Fintech', geoScore: 81, citationWinRate: 77, zeroClickResilience: 75, trend: 'up', trendDelta: 2, scanCount: 9 },
  { rank: 149, domain: 'freshworks.com', category: 'SaaS/Tools', geoScore: 80, citationWinRate: 76, zeroClickResilience: 74, trend: 'flat', trendDelta: 0, scanCount: 13 },
  { rank: 150, domain: 'gorgias.com', category: 'E-Commerce', geoScore: 80, citationWinRate: 76, zeroClickResilience: 74, trend: 'up', trendDelta: 2, scanCount: 11 },
  { rank: 151, domain: 'attentive.com', category: 'E-Commerce', geoScore: 80, citationWinRate: 75, zeroClickResilience: 73, trend: 'flat', trendDelta: 0, scanCount: 10 },
  { rank: 152, domain: 'mercadolibre.com', category: 'E-Commerce', geoScore: 80, citationWinRate: 76, zeroClickResilience: 74, trend: 'up', trendDelta: 1, scanCount: 15 },
  { rank: 153, domain: 'woocommerce.com', category: 'E-Commerce', geoScore: 80, citationWinRate: 76, zeroClickResilience: 74, trend: 'down', trendDelta: -1, scanCount: 16 },
  { rank: 154, domain: 'squarespace.com', category: 'E-Commerce', geoScore: 80, citationWinRate: 76, zeroClickResilience: 74, trend: 'flat', trendDelta: 0, scanCount: 18 },
  { rank: 155, domain: 'printful.com', category: 'E-Commerce', geoScore: 80, citationWinRate: 75, zeroClickResilience: 73, trend: 'flat', trendDelta: 0, scanCount: 12 },
  { rank: 156, domain: 'faire.com', category: 'E-Commerce', geoScore: 80, citationWinRate: 76, zeroClickResilience: 74, trend: 'up', trendDelta: 2, scanCount: 11 },
  { rank: 157, domain: 'gymshark.com', category: 'E-Commerce', geoScore: 80, citationWinRate: 75, zeroClickResilience: 74, trend: 'up', trendDelta: 1, scanCount: 13 },
  { rank: 158, domain: 'allbirds.com', category: 'E-Commerce', geoScore: 79, citationWinRate: 74, zeroClickResilience: 72, trend: 'down', trendDelta: -2, scanCount: 11 },
  { rank: 159, domain: 'warbyparker.com', category: 'E-Commerce', geoScore: 79, citationWinRate: 74, zeroClickResilience: 73, trend: 'flat', trendDelta: 0, scanCount: 12 },
  { rank: 160, domain: 'glossier.com', category: 'E-Commerce', geoScore: 79, citationWinRate: 74, zeroClickResilience: 72, trend: 'down', trendDelta: -1, scanCount: 10 },
  { rank: 161, domain: 'alloy.com', category: 'Fintech', geoScore: 79, citationWinRate: 74, zeroClickResilience: 72, trend: 'flat', trendDelta: 0, scanCount: 8 },
  { rank: 162, domain: 'persona.com', category: 'Fintech', geoScore: 79, citationWinRate: 75, zeroClickResilience: 73, trend: 'up', trendDelta: 2, scanCount: 9 },
  { rank: 163, domain: 'lithic.com', category: 'Fintech', geoScore: 79, citationWinRate: 74, zeroClickResilience: 72, trend: 'flat', trendDelta: 0, scanCount: 7 },
  { rank: 164, domain: 'ripple.com', category: 'Fintech', geoScore: 79, citationWinRate: 74, zeroClickResilience: 72, trend: 'down', trendDelta: -1, scanCount: 12 },
  { rank: 165, domain: 'rows.com', category: 'SaaS/Tools', geoScore: 79, citationWinRate: 75, zeroClickResilience: 73, trend: 'up', trendDelta: 3, scanCount: 9 },
  { rank: 166, domain: 'cvent.com', category: 'SaaS/Tools', geoScore: 78, citationWinRate: 73, zeroClickResilience: 71, trend: 'down', trendDelta: -2, scanCount: 8 },
  { rank: 167, domain: 'svgrepo.com', category: 'SaaS/Design', geoScore: 78, citationWinRate: 73, zeroClickResilience: 71, trend: 'flat', trendDelta: 0, scanCount: 10 },
  { rank: 168, domain: 'typeface.ai', category: 'SaaS/Design', geoScore: 78, citationWinRate: 74, zeroClickResilience: 72, trend: 'up', trendDelta: 2, scanCount: 7 },
  { rank: 169, domain: 'kittl.com', category: 'SaaS/Design', geoScore: 78, citationWinRate: 74, zeroClickResilience: 72, trend: 'up', trendDelta: 3, scanCount: 8 },
  { rank: 170, domain: 'invisionapp.com', category: 'SaaS/Design', geoScore: 77, citationWinRate: 71, zeroClickResilience: 69, trend: 'down', trendDelta: -4, scanCount: 11 },
  { rank: 171, domain: 'weightsandbiases.com', category: 'AI/Tech', geoScore: 79, citationWinRate: 75, zeroClickResilience: 73, trend: 'up', trendDelta: 1, scanCount: 9 },
  { rank: 172, domain: 'copy.ai', category: 'AI/Tech', geoScore: 78, citationWinRate: 73, zeroClickResilience: 71, trend: 'down', trendDelta: -2, scanCount: 11 },
  { rank: 173, domain: 'suno.com', category: 'AI/Tech', geoScore: 79, citationWinRate: 75, zeroClickResilience: 73, trend: 'up', trendDelta: 4, scanCount: 8 },
  { rank: 174, domain: 'krea.ai', category: 'AI/Tech', geoScore: 78, citationWinRate: 74, zeroClickResilience: 72, trend: 'up', trendDelta: 3, scanCount: 7 },
  { rank: 175, domain: 'claude.ai', category: 'AI/Tech', geoScore: 94, citationWinRate: 93, zeroClickResilience: 91, trend: 'up', trendDelta: 4, scanCount: 18 },
  { rank: 176, domain: 'deepmind.google', category: 'AI/Tech', geoScore: 95, citationWinRate: 94, zeroClickResilience: 92, trend: 'up', trendDelta: 2, scanCount: 16 },
  { rank: 177, domain: 'stackblitz.com', category: 'Developer', geoScore: 82, citationWinRate: 79, zeroClickResilience: 77, trend: 'up', trendDelta: 2, scanCount: 11 },
  { rank: 178, domain: 'codesandbox.io', category: 'Developer', geoScore: 81, citationWinRate: 77, zeroClickResilience: 75, trend: 'flat', trendDelta: 0, scanCount: 12 },
  { rank: 179, domain: 'gitpod.io', category: 'Developer', geoScore: 80, citationWinRate: 76, zeroClickResilience: 74, trend: 'down', trendDelta: -1, scanCount: 10 },
  { rank: 180, domain: 'railway.com', category: 'Developer', geoScore: 82, citationWinRate: 78, zeroClickResilience: 76, trend: 'up', trendDelta: 2, scanCount: 9 },
  { rank: 181, domain: 'segment.io', category: 'Developer', geoScore: 81, citationWinRate: 77, zeroClickResilience: 75, trend: 'flat', trendDelta: 0, scanCount: 8 },
  { rank: 182, domain: 'replit.com', category: 'Developer', geoScore: 85, citationWinRate: 82, zeroClickResilience: 80, trend: 'up', trendDelta: 3, scanCount: 15 },
  { rank: 183, domain: 'v0.dev', category: 'AI/Tech', geoScore: 88, citationWinRate: 86, zeroClickResilience: 84, trend: 'up', trendDelta: 5, scanCount: 14 },
  { rank: 184, domain: 'bolt.new', category: 'AI/Tech', geoScore: 87, citationWinRate: 85, zeroClickResilience: 83, trend: 'up', trendDelta: 6, scanCount: 13 },
  { rank: 185, domain: 'midjourney.art', category: 'SaaS/Design', geoScore: 80, citationWinRate: 76, zeroClickResilience: 74, trend: 'flat', trendDelta: 0, scanCount: 7 },
];

export const DEFAULT_LEADERBOARD_ENTRIES: LeaderboardEntry[] = [...RAW_ENTRIES]
  .sort((a, b) => b.geoScore - a.geoScore)
  .map((entry, index) => ({
    ...entry,
    rank: index + 1,
  }));
