export type EngineType = 'perplexity' | 'chatgpt' | 'claude' | 'gemini';

export interface EngineScore {
  engine: EngineType;
  name: string;
  /** Blended GEO score for this engine (0-100). Derived from structural analysis
   * when no API key is provided; blended with live confidence when a key is used. */
  score: number;
  /** Estimated citation probability (0-100%) based on score. Live-calibrated when API key is available. */
  citationProbability: number;
  sentimentRating: 'High Authority' | 'Moderate' | 'Low / Excluded';
  /** True when score and citationProbability came from a real live engine API query */
  isLiveQuery?: boolean;
  /** Excerpt from live engine response mentioning the domain, if any */
  citationSnippet?: string;
  /** Exact probe query dispatched to the foundation model */
  probeQuery?: string;
  /** Whether the model actually cited or referenced the domain */
  isCited?: boolean;
  /** Actual citation URL returned in web search sources */
  citationUrl?: string;
  /** Granular citation tier: directly cited with attribution vs known in knowledge graph vs omitted */
  citationStatus?: 'actively_cited' | 'entity_recognized' | 'omitted';
  /** Foundation model role description (e.g. Live Web Retrieval, Entity Knowledge Graph) */
  modelRole?: string;
  /** Latency in milliseconds of the live probe */
  latencyMs?: number;
  /** Timestamp when the live probe was performed */
  testedAt?: string;
  /** Whether this probe result was returned from cache */
  isCached?: boolean;
}

export interface EntityNode {
  name: string;
  type: 'Brand' | 'Product' | 'Industry' | 'Key Feature' | 'Competitor';
  confidence: number;
  groundedInKG: boolean;
}

/**
 * Result returned by a real AI engine API query for a domain.
 * Used to enrich EngineScore with live data when the user has configured API keys.
 */
export interface EngineQueryResult {
  engine: EngineType;
  /** True = live API call succeeded; false = API call failed / no key */
  isLiveQuery: boolean;
  /** Whether the engine's response explicitly mentioned or cited the domain */
  isCited: boolean;
  /** Raw confidence derived from response quality (0–1) */
  confidence: number;
  /** Short excerpt from the engine response mentioning the domain */
  citationSnippet?: string;
  /** Error message if the API call failed */
  error?: string;
}

export interface Recommendation {
  id: string;
  category: 'Schema' | 'Information Gain' | 'Agentic API' | 'Vector Density';
  priority: 'CRITICAL' | 'HIGH' | 'MEDIUM';
  title: string;
  description: string;
  impact: string;
  codeSnippet?: string;
  /** AI-enriched: effort required (low/medium/high) */
  effort?: 'LOW' | 'MEDIUM' | 'HIGH';
  /** AI-enriched: quick-win / strategic / nice-to-have classification */
  effortImpact?: 'QUICK_WIN' | 'STRATEGIC' | 'NICE_TO_HAVE';
}

export interface LiveExtractionMetadata {
  isLiveScanned: boolean;
  httpStatus?: number;
  extractedTitle?: string;
  extractedDescription?: string;
  schemaJsonLdCount: number;
  h1Count: number;
  h2Count: number;
  tableCount: number;
  wordCount: number;
  hasRobotsIndexingAllowed: boolean;
  detectedSchemas: string[];
}

export interface AiTailoredSchema {
  type: string;
  title: string;
  description: string;
  jsonLd: string;
}

export interface AiContentRewrite {
  originalIssue: string;
  suggestedCopy: string;
  rationale: string;
}

export interface AiReportInsights {
  modelUsed: string;
  generatedAt: string;
  executiveSummary: string;
  topicalAuthorityScore: number;
  citationRiskFactors: string[];
  tailoredSchemas: AiTailoredSchema[];
  suggestedAgentManifest?: string;
  contentRewrites: AiContentRewrite[];
  competitorStrategies: string[];
}

export interface GeoAuditReport {
  domain: string;
  url: string;
  analyzedAt: string;
  overallGeoScore: number; // 0 - 100
  zeroClickResilience: number; // 0 - 100
  informationGainScore: number; // 0 - 100
  entityDisambiguationScore: number; // 0 - 100
  vectorReadinessScore: number; // 0 - 100
  engineBreakdown: EngineScore[];
  detectedEntities: EntityNode[];
  recommendations: Recommendation[];
  summary: string;
  liveMetadata?: LiveExtractionMetadata;
  /** 'live_crawl' = Jina crawl succeeded; 'structural_estimate' = domain-hash fallback */
  dataSource?: 'live_crawl' | 'structural_estimate';
  /** Deep AI semantic analysis generated by CiteRoute Engine */
  aiInsights?: AiReportInsights;
  /** Whether this report was served from cache */
  isCached?: boolean;
  /** Timestamp when the cached report was originally generated */
  cachedAt?: string;
  /** Cache age in milliseconds */
  cacheAgeMs?: number;
  /** Machine-readable protocols verified for this domain */
  agentProtocols?: {
    hasLlmsTxt?: boolean;
    hasAgentJson?: boolean;
    hasSitemap?: boolean;
    hasRobotsTxt?: boolean;
  };
}

export interface ScoreHistoryPoint {
  date: string;
  score: number;
}

export interface WatchedDomain {
  id: string;
  domain: string;
  url: string;
  lastGeoScore: number;
  previousGeoScore?: number;
  addedAt: string;
  lastScannedAt: string;
  zeroClickResilience: number;
  citationProbability: number;
  status: 'OPTIMAL' | 'MODERATE' | 'AT_RISK';
  scoreHistory?: ScoreHistoryPoint[];
}

export interface AgentServiceEndpoint {
  id: string;
  name: string;
  path: string;
  method: 'GET' | 'POST';
  description: string;
  authRequired: boolean;
  pricingType: 'free' | 'per_call' | 'subscription' | 'checkout';
}

export interface AgentProductSchema {
  id: string;
  name: string;
  sku: string;
  price: number;
  currency: string;
  category: string;
  inStock: boolean;
  directAgentCheckoutUrl: string;
}

export interface AgentManifest {
  version: string;
  siteName: string;
  domain: string;
  description: string;
  organization: {
    legalName: string;
    foundedYear: number;
    headquarters: string;
    contactEmail: string;
  };
  capabilities: string[];
  endpoints: AgentServiceEndpoint[];
  products?: AgentProductSchema[];
  semanticVectors: {
    embeddingsUrl: string;
    contextSizeTokens: number;
    lastUpdated: string;
  };
  accessPolicy: {
    allowAgentCrawlers: boolean;
    allowDirectTransactions: boolean;
    rateLimitPerMin: number;
  };
}



export interface LiveTelemetryEvent {
  id: string;
  timestamp: string;
  type: 'AI_CITATION' | 'AGENT_TX' | 'P2P_MESH_CLICK' | 'GEO_INDEX_PING';
  source: string;
  destinationUrl: string;
  intent: string;
  geoScoreAtTime: number;
  settlementValue?: number;
}
